<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="course" nsURI="platform:/plugin/no.espegu.course.model/model/Courses.ecore"
    nsPrefix="no.espegu">
  <eClassifiers xsi:type="ecore:EClass" name="School">
    <eStructuralFeatures xsi:type="ecore:EReference" name="programmes" upperBound="-1"
        eType="#//Program"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Program">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="semesters" upperBound="-1"
        eType="#//Semester"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Course" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="semester" eType="#//Semester"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="points" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Semester">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="courses" upperBound="-1"
        eType="#//Course"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MandatoryCourse" eSuperTypes="#//Course"/>
  <eClassifiers xsi:type="ecore:EClass" name="ElectiveCourse" eSuperTypes="#//Course"/>
</ecore:EPackage>
