<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="course" nsURI="platform:/plugin/no.espegu.course.model/model/Courses.ecore"
    nsPrefix="no.espegu">
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="validationDelegates" value="http://www.eclipse.org/acceleo/query/1.0"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="School">
    <eStructuralFeatures xsi:type="ecore:EReference" name="programs" upperBound="-1"
        eType="#//Program" containment="true" eOpposite="#//Program/school"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="students" upperBound="-1"
        eType="#//Student" containment="true" eOpposite="#//Student/school"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Program">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="requiredCredits" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="school" eType="#//School"
        eOpposite="#//School/programs"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="programYears" upperBound="-1"
        eType="#//ProgramYear" containment="true" eOpposite="#//ProgramYear/program"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Course">
    <eOperations name="isSameCourse" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="otherCourse" lowerBound="1" eType="#//Course"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="credits" eType="#//CourseCredit"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="level" eType="#//CourseLevel"
        defaultValueLiteral="First Degree Subject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="Add a description to this course."/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="taughtInSemester" eType="#//SemesterType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="code" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Student">
    <eStructuralFeatures xsi:type="ecore:EReference" name="studyPlan" eType="#//StudyPlan"
        eOpposite="#//StudyPlan/student"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="Ola Nordmann"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="school" eType="#//School"
        eOpposite="#//School/students"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StudyPlan">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="hasRequiredCreditsForProgram"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="semesters" upperBound="-1"
        eType="#//StudyPlanSemester" containment="true" eOpposite="#//StudyPlanSemester/studyPlan"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="student" eType="#//Student"
        eOpposite="#//Student/studyPlan"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="selectedProgram" eType="#//SelectableProgramSpecialization"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Semester">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="year" eType="#//Year" defaultValueLiteral="2020"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="semesterType" eType="#//SemesterType"
        defaultValueLiteral="Autumn"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="teachedInSemester" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" unsettable="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SelectableProgramSpecialization">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="semesters" upperBound="-1"
        eType="#//ProgramSemester" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="programYear" eType="#//ProgramYear"
        eOpposite="#//ProgramYear/selectablePrograms"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subSpecializations" upperBound="-1"
        eType="#//SelectableProgramSpecialization" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StudyPlanSemester" eSuperTypes="#//Semester">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="isAllCoursesTaughtThisSemester isValidRelatedProgramSemester"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/acceleo/query/1.0">
      <details key="isAllCoursesTaughtThisSemester" value="self.selectedCourses -> collect(selectedCourse | selectedCourse.taughtInSemester) -> forAll(semester | semester == self.semesterType)"/>
    </eAnnotations>
    <eOperations name="addCourseToSemester" eType="#//StudyPlanSemester" eExceptions="#//CourseAlreadyExistsException">
      <eParameters name="course" eType="#//Course"/>
    </eOperations>
    <eOperations name="getAllCoursesInSemester">
      <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEList">
        <eTypeArguments/>
      </eGenericType>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="selectedCourses" upperBound="-1"
        eType="#//Course" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="totalCredits" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        changeable="false" volatile="true" transient="true" unsettable="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="studyPlan" lowerBound="1"
        eType="#//StudyPlan" eOpposite="#//StudyPlan/semesters"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="relatedProgramSemester"
        lowerBound="1" eType="#//ProgramSemester"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProgramSemester" eSuperTypes="#//Semester">
    <eStructuralFeatures xsi:type="ecore:EReference" name="mandatoryCourses" upperBound="-1"
        eType="#//Course" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="electiveCourses" upperBound="-1"
        eType="#//Course" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProgramYear">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="year" eType="#//Year" defaultValueLiteral="2020"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="program" eType="#//Program"
        eOpposite="#//Program/programYears"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="selectablePrograms" lowerBound="1"
        upperBound="-1" eType="#//SelectableProgramSpecialization" containment="true"
        eOpposite="#//SelectableProgramSpecialization/programYear"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SemesterType" instanceTypeName="semesterType">
    <eLiterals name="AUTUMN" literal="Autumn"/>
    <eLiterals name="SPRING" value="1" literal="Spring"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CourseLevel">
    <eLiterals name="FIRST_DEGREE" value="1" literal="First Degree Subject"/>
    <eLiterals name="SECOND_DEGREE" value="2" literal="Second Degree Subject"/>
    <eLiterals name="THIRD_DEGREE" value="3" literal="Third Degree Subject"/>
    <eLiterals name="HIGHER_DEGREE" value="4" literal="Higher Degree Subject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Year" instanceClassName="java.lang.String">
    <eAnnotations source="http://www.eclipse.org/acceleo/query/1.0">
      <details key="hasCorrectYearFormat" value="self.size() == 4 AND self.matches('[0-9]+')"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="hasCorrectYearFormat"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="CourseCredit" instanceClassName="java.lang.Float">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="isGreaterOrEqualToZero"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="CourseAlreadyExistsException" instanceClassName="java.lang.RuntimeException"/>
</ecore:EPackage>
